"""added phone number field

Revision ID: 164ce38f24b8
Revises: e19c6feb0866
Create Date: 2022-12-18 04:42:25.088263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '164ce38f24b8'
down_revision = 'e19c6feb0866'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
